apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-puldmoza
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-puldmoza:c6a208d10c17942cd81adfd79c6095f0bc44d9ca@sha256:11c90a20d713e28974f3bf2fdb58a93367bb22c0ec3a117b531faaf6ad489e28
          name: container-image
